'use client';

import { useEffect, useRef, useState, useMemo } from 'react';
import { Activity, ArrowRight, ArrowUpRight, Bookmark, Check, ChevronDown, ChevronRight, CircleHelp, Expand, FlaskConical, Glasses, Layers3, LayoutDashboard, MessageSquare, Plus, Radio, RotateCcw, ShieldCheck, SlidersHorizontal, Sparkles, Target, TrendingUp, Wallet, X } from 'lucide-react';
import { Slider } from '@/components/ui/slider';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { registerSimulationTools } from '@/lib/webmcp';
import { forecast, money, scenarioLabels, type Scenario } from '@/lib/simulation';

const assets = [
  {name:'纳指 ETF', code:'513100', allocation:30, price:'1.862', change:'+1.84%', color:'#9f8bff', shape:[28,25,29,20,22,14,17,8,12,5]},
  {name:'沪深 300 ETF', code:'510300', allocation:20, price:'4.086', change:'+0.62%', color:'#79adff', shape:[25,20,24,18,21,15,18,12,16,11]},
  {name:'创业板 ETF', code:'159915', allocation:18, price:'2.341', change:'−0.86%', color:'#52ccb9', shape:[8,14,10,19,15,24,19,29,24,30]},
  {name:'黄金 ETF', code:'518880', allocation:12, price:'7.258', change:'+0.35%', color:'#e3bb76', shape:[28,25,27,22,25,17,20,13,17,12]},
];
const events = [
  {title:'科技板块波动扩大，留意组合集中度',type:'市场观察',time:'14:28',asset:'纳指 ETF',icon:Activity,desc:'演示事件：假设科技板块波动上升。当前纳指与创业板合计占账户 48%，需一起评估相关风险。此消息为虚构演示内容。'},
  {title:'黄金资产走强，观察组合分散效果',type:'资产动态',time:'13:45',asset:'黄金 ETF',icon:TrendingUp,desc:'演示事件：假设黄金走势走强。黄金并非始终与股票反向波动，需比较组合不同情景。此消息为虚构演示内容。'},
  {title:'月度策略复核：检查现金与风险预算',type:'策略日历',time:'09:30',asset:'我的组合',icon:Target,desc:'演示计划：复核投资期限、资金用途、持仓集中度与模拟假设。仅保存方案不会修改实际持仓。'},
];
type Message={role:'user'|'assistant',text:string};
type SavedPlan={allocation:number;days:number;scenario:Scenario;deposit:number;at:string};
function MiniChart({points,color}:{points:number[];color:string}){return <svg viewBox="0 0 90 38" aria-hidden="true"><path d={points.map((y,i)=>`${i?'L':'M'} ${i*10} ${y}`).join(' ')} fill="none" stroke={color} strokeWidth="1.8" strokeLinejoin="round"/></svg>}
function Projection({allocation,days,scenario,selected,deposit=0,large=false}:{allocation:number;days:number;scenario:Scenario;selected:number;deposit?:number;large?:boolean}){
 const [hover,setHover]=useState<number|null>(null);
 const seed=selected+2;
 const paths=useMemo(()=>{
  const hist=Array.from({length:65},(_,i)=>[i*6.25,232-i*1.19+Math.sin(i*1.18+seed)*8+Math.sin(i*.36)*11]);hist[64]=[400,164];
  const path=(points:number[][])=>points.map(([x,y],i)=>`${i?'L':'M'}${x.toFixed(2)},${y.toFixed(2)}`).join(' ');
  const amp=(allocation/80)*Math.sqrt(days/20);
  const bound=Math.max(12,Math.ceil(Math.max(Math.abs(forecast(allocation,days,'bear',deposit).percent),Math.abs(forecast(allocation,days,'bull',deposit).percent))/6)*6);
  const futureY=(i:number,sc:Scenario)=>164-forecast(allocation,Math.max(.0001,i/40*days),sc,deposit).percent*128/bound;
  const futures=([-1,0,1] as const).map((k)=>Array.from({length:41},(_,i)=>{const t=i/40;return [400+t*290,futureY(i,(['bear','base','bull'] as Scenario[])[k+1])+Math.sin(i*.68+seed)*3*Math.sin(Math.PI*t)*amp]}));
  return {ticks:[100+bound,100+bound/2,100,100-bound/2,100-bound],history:path(hist),fill:path(hist)+' L400,304 L0,304 Z',future:futures.map(path),band:path(futures[2])+' '+path([...futures[0]].reverse()).replace('M','L')+' Z',ghosts:Array.from({length:18},(_,n)=>path(Array.from({length:41},(_,i)=>{const t=i/40;return [400+t*290,futureY(i,'bear')*(1-n/17)+futureY(i,'bull')*(n/17)+(Math.sin(i*.43+n)*8+Math.sin(i*.93+n*3)*4)*Math.sin(Math.PI*t)*amp]})))};
 },[allocation,days,seed,deposit]);
 const active=scenario==='bear'?0:scenario==='base'?1:2;
 return <div className={'projection '+(large?'large':'')} onMouseLeave={()=>setHover(null)}>
  <div className="chart-top-labels"><span><i className="legend-dot purple"/>历史示意</span><span className="future-label"><Sparkles size={12}/>组合未来 {days} 日 · 假设推演</span></div>
  <svg viewBox="0 0 780 345" role="img" aria-label={`${selected<0?'组合':assets[selected].name}历史示意和未来${days}日三种假设情景。非实际行情，非概率预测。`} onMouseMove={e=>{const r=e.currentTarget.getBoundingClientRect();setHover(Math.max(0,Math.min(690,(e.clientX-r.left)/r.width*780)))}}>
   <defs><linearGradient id={large?'histFillL':'histFill'} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#8c72f6" stopOpacity=".22"/><stop offset="100%" stopColor="#8c72f6" stopOpacity="0"/></linearGradient><linearGradient id={large?'forecastFillL':'forecastFill'} x1="0" x2="1"><stop stopColor="#8470ed" stopOpacity=".025"/><stop offset="100%" stopColor="#8973f9" stopOpacity=".16"/></linearGradient><filter id={large?'glowL':'glow'}><feGaussianBlur stdDeviation="3"/></filter><clipPath id={large?'plotL':'plot'}><rect width="705" height="307"/></clipPath></defs>
   {[36,100,164,228,292].map((y,i)=><g key={y}><line x1="0" x2="700" y1={y} y2={y} stroke="#242633" strokeDasharray="3 5"/><text x="718" y={y+4} fill="#777d92" fontSize="12">{paths.ticks[i]}</text></g>)}
   {[100,200,300,500,600].map(x=><line key={x} x1={x} x2={x} y1="24" y2="305" stroke="#1c1e2b"/>)}
   <g clipPath={`url(#${large?'plotL':'plot'})`}><path d={paths.fill} fill={`url(#${large?'histFillL':'histFill'})`}/><path d={paths.history} stroke="#9d87ff" strokeWidth="7" opacity=".22" fill="none" filter={`url(#${large?'glowL':'glow'})`}/><path d={paths.history} stroke="#ac97ff" strokeWidth="2.5" fill="none"/>
   <path d={paths.band} fill={`url(#${large?'forecastFillL':'forecastFill'})`}/>{paths.ghosts.map((d,i)=><path d={d} key={i} stroke="#9b81f0" strokeWidth=".75" opacity=".13" fill="none"/>)}
   {paths.future.map((d,i)=><path key={i} d={d} fill="none" stroke={['#8496b9','#b098ff','#56cbb2'][i]} strokeWidth={active===i?2.5:1.4} strokeDasharray={active===i?'6 4':'3 5'} opacity={active===i?1:.65}/>)}
   </g><line x1="400" x2="400" y1="15" y2="304" stroke="#7a688f" strokeDasharray="4 5"/><circle cx="400" cy="164" r="10" fill="#a28aff" opacity=".15"/><circle cx="400" cy="164" r="4" fill="#d0bcff"/>
   <rect x="373" y="305" width="54" height="23" rx="5" fill="#30253f"/><text x="400" y="321" textAnchor="middle" fontSize="11" fill="#d2bbf9">今天</text>
   {[[0,'08.12'],[135,'08.21'],[265,'08.31'],[540,`+${Math.round(days/2)}日`],[685,`+${days}日`]].map(([x,t])=><text key={t} x={Number(x)+4} y="321" fontSize="12" fill="#777d92" textAnchor={Number(x)>600?'end':'start'}>{t}</text>)}
   {hover!==null&&<g><line x1={hover} x2={hover} y1="20" y2="299" stroke="#a79cbe" opacity=".4"/><rect x={Math.min(hover+10,515)} y="30" width="167" height="36" rx="6" fill="#252234" stroke="#504568"/><text x={Math.min(hover+22,527)} y="52" fontSize="12" fill="#e1dbea">{hover<400?'历史净值示意 · 基准 100':`${scenarioLabels[scenario]} · 非概率预测`}</text></g>}
  </svg>
  <div className="chart-legend"><span><i style={{background:'#56cbb2'}}/>上涨情景</span><span><i style={{background:'#b098ff'}}/>震荡情景</span><span><i style={{background:'#8496b9'}}/>下跌情景</span><small>归一化示意 · 非真实历史 / 预测</small></div>
 </div>
}
export default function Home(){
 const [selected,setSelected]=useState(-1),[allocation,setAllocation]=useState(65),[days,setDays]=useState(20),[scenario,setScenario]=useState<Scenario>('base'),[deposit,setDeposit]=useState(0);
 const [dialog,setDialog]=useState<'profile'|'plan'|'saved'|'chart'|'event'|'method'|null>(null),[eventIndex,setEventIndex]=useState(0),[triggered,setTriggered]=useState(false),[saved,setSaved]=useState<SavedPlan|null>(null),[notice,setNotice]=useState('');
 const [input,setInput]=useState(''),[messages,setMessages]=useState<Message[]>([]),[chatOpen,setChatOpen]=useState(true),[pending,setPending]=useState(false),[risk,setRisk]=useState('稳健成长'),[months,setMonths]=useState('12 个月'),[depositDraft,setDepositDraft]=useState('50000');
 const chatEnd=useRef<HTMLDivElement>(null);const inputRef=useRef<HTMLTextAreaElement>(null);const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const result=forecast(allocation,days,scenario,deposit),original=forecast(80,days,scenario,deposit);
 const focusName=selected<0?'我的组合':assets[selected].name;
 useEffect(()=>{if(window.matchMedia('(max-width:1050px)').matches)setChatOpen(false);try{const raw=localStorage.getItem('owlmate-plan-v1');if(raw){const p=JSON.parse(raw);if(p&&[5,20,60].includes(p.days)&&p.allocation>=0&&p.allocation<=100&&['bull','base','bear'].includes(p.scenario)&&Number.isFinite(p.deposit)&&p.deposit>=0&&typeof p.at==='string')setSaved(p);}}catch{}return()=>{if(timer.current)clearTimeout(timer.current)}},[]);
 useEffect(()=>registerSimulationTools({setAllocation,setDays,setScenario}),[]);
 useEffect(()=>{if(messages.length)chatEnd.current?.scrollIntoView({behavior:'smooth',block:'nearest'})},[messages,pending]);
 useEffect(()=>{if(!notice)return;const t=setTimeout(()=>setNotice(''),4000);return()=>clearTimeout(t)},[notice]);
 function save(){const p={allocation,days,scenario,deposit,at:new Date().toLocaleString('zh-CN')};setSaved(p);try{localStorage.setItem('owlmate-plan-v1',JSON.stringify(p));setNotice('试算方案已保存在本机，真实持仓未改变。')}catch{setNotice('方案已保存在当前页面；浏览器存储不可用。')}}
 function ask(question:string){if(pending||!question.trim())return;setChatOpen(true);setMessages(m=>[...m,{role:'user',text:question.trim()}]);setInput('');setPending(true);let answer='';const match=question.match(/(\d{1,3})\s*[%％]/);
 if(match&&/仓位|配置|降到|调到/.test(question)){const n=Number(match[1]);if(n<=100){setAllocation(n);answer=`已把组合的风险资产模拟仓位调整到 ${n}%，剩余 ${100-n}% 保留现金。中央图表与情景结果已同步更新。这是组合级试算，尚未保存，也未修改真实持仓。`}else answer='仓位需要在 0% 到 100% 之间。演示版不使用杠杆，请输入范围内的比例。'}
 else if(/下跌|跌了|压力/.test(question)){setScenario('bear');answer=`已切换到下跌情景。按当前 ${allocation}% 仓位和 ${days} 个交易日的假设，组合期末变化为 ${money(forecast(allocation,days,'bear',deposit).pnl)}。情景由预设资产涨跌假设计算，不代表发生概率，也不包含止损执行保证。`}
 else if(/保存/.test(question)){answer='你可以点击建议卡的「保存试算方案」。保存后可以在顶部书签中查看；保存计划不会自动交易。'}
 else if(/新闻|事件|发生|科技/.test(question)){answer='当前展示的是演示事件：科技板块波动扩大。纳指 ETF 与创业板 ETF 合计占账户 48%，可以先比较降低总风险资产仓位后的影响。此事件并非真实新闻，尚未接入实时资讯。'}
 else if(/买|资金|万元|万块/.test(question)){setDialog('plan');answer='已打开新资金试算。填写新增金额后，会以「当前资产＋新增资金」为基数计算目标配置。这里不直接修改账户余额，也不提供实时选股。'}
 else if(/为什么|风险|建议|持仓|分析/.test(question)){answer=`${focusName}的分析基于示例账户。纳指与创业板合计占账户 48%，存在科技风格集中。65% 是供比较的演示配置，不是凯利计算或真实投资建议。你可以调整仓位，并比较上涨、震荡、下跌情景，判断现金和风险的变化。`}
 else answer='我目前是交互演示助手，支持解释示例持仓、切换下跌情景、按百分比调整组合仓位，以及打开新增资金试算。你可以试试「把组合仓位调到 60%」。开放式研究与实时行情将在后续接入。';
 timer.current=setTimeout(()=>{setMessages(m=>[...m,{role:'assistant',text:answer}]);setPending(false)},550);
 }
 return <div className="app-shell">
  <nav className="icon-rail" aria-label="页面区域"><a href="#overview" className="brand-symbol" aria-label="OwlMate 首页"><Glasses size={29}/></a><div className="rail-links"><a href="#overview" className="rail-item active" aria-label="投资驾驶舱" title="投资驾驶舱"><LayoutDashboard/></a><a href="#holdings" className="rail-item" aria-label="我的持仓" title="我的持仓"><Wallet/></a><a href="#simulation" className="rail-item" aria-label="情景实验室" title="情景实验室"><FlaskConical/></a><a href="#events" className="rail-item" aria-label="事件雷达" title="事件雷达"><Radio/></a><button className="rail-item" aria-label="已保存方案" title="已保存方案" onClick={()=>setDialog('saved')}><Bookmark/></button></div><button className="rail-item rail-bottom" aria-label="演示说明" title="演示说明" onClick={()=>setDialog('method')}><CircleHelp/></button><button className="avatar" aria-label="投资画像" onClick={()=>setDialog('profile')}>O</button></nav>
  <div className="workspace" id="overview"><header className="topbar"><div className="wordmark">OwlMate<span className="brand-beta">BETA</span></div><span className="header-divider"/><span className="workspace-label">个人投资工作台</span><div className="header-right"><span className="demo-badge"><i/>交互演示</span><span className="snapshot">09.09 · 14:30 数据快照</span><button className="icon-button" aria-label="查看已保存方案" onClick={()=>setDialog('saved')}><Bookmark size={18}/>{saved&&<i className="notify-dot"/>}</button><button className="account-button" onClick={()=>setDialog('profile')}><span className="small-avatar">O</span><span>演示账户</span><ChevronDown size={14}/></button></div></header>
  <div className="market-ticker"><span className="market-state"><i/>市场快照</span>{[['上证指数','3,862.41','+0.46%'],['沪深 300','4,421.68','+0.62%'],['创业板指','2,816.52','−0.86%'],['黄金现货','3,642.80','+0.35%']].map(([n,v,c])=><div className="ticker-item" key={n}><span>{n}</span><b>{v}</b><em className={c.startsWith('+')?'up':'down'}>{c}</em></div>)}<span className="ticker-note">全部为示例数据</span></div>
  <main className={'main-layout '+(!chatOpen?'chat-collapsed':'')}><div className="dashboard"><div className="page-heading"><div><div className="eyebrow">YOUR INVESTMENT, IN PERSPECTIVE</div><h1>投资驾驶舱<span className="heading-dot"/></h1><p>看清当下的资产，探索未来的每一种可能。</p></div><button className="primary-button" onClick={()=>setDialog('plan')}><Plus size={17}/>新建投资计划</button></div>
   <section className="stats-grid" aria-label="资产摘要"><div className="stat-card net-worth"><div className="stat-label">总资产 <Wallet size={15}/></div><div className="stat-value"><span>¥</span>1,286,400<span className="decimal">.00</span></div><div className="stat-foot"><span className="up"><ArrowUpRight size={13}/>累计 +12.86%</span><span>示例净值</span></div><div className="tiny-bars" aria-hidden="true">{[10,15,12,21,18,26,22,28,25,35,31,38,34,43,39,47].map((h,i)=><i key={i} style={{height:h}}/>)}</div></div><div className="stat-card"><div className="stat-label">今日盈亏 <TrendingUp size={15}/></div><div className="stat-value up"><span>+</span>8,568<span className="decimal">.00</span></div><div className="stat-foot"><span className="up">+0.67%</span><span>较上一交易日</span></div></div><div className="stat-card"><div className="stat-label">风险资产仓位 <Layers3 size={15}/></div><div className="stat-value">80.0<span className="decimal">%</span></div><div className="stat-foot"><span className="allocation-line"><i/></span><span>现金 20%</span></div></div><div className="stat-card"><div className="stat-label">组合当前回撤 <ShieldCheck size={15}/></div><div className="stat-value">−4.28<span className="decimal">%</span></div><div className="stat-foot"><span className="mint"><i className="small-dot"/>监控中</span><span>示例预警线 −10%</span></div></div></section>
   <div className="analysis-grid"><section className="panel holdings-panel" id="holdings"><div className="panel-heading"><h2>我的持仓 <span>04</span></h2><button className="icon-button" aria-label="编辑投资画像" onClick={()=>setDialog('profile')}><SlidersHorizontal size={15}/></button></div><button className={'portfolio-select '+(selected===-1?'selected':'')} onClick={()=>setSelected(-1)}><span className="portfolio-icon"><Layers3 size={18}/></span><span><b>全部资产</b><small>组合视角</small></span><ChevronRight size={15}/></button><div className="holdings-list">{assets.map((a,i)=><button key={a.code} className={'holding '+(selected===i?'selected':'')} onClick={()=>setSelected(i)}><div className="holding-name"><i style={{background:a.color}}/><b>{a.name}</b><span>{a.allocation}%</span></div><div className="holding-sub"><small>{a.code}</small><MiniChart points={a.shape} color={a.change.startsWith('+')?'#e08d95':'#54bba6'}/><em className={a.change.startsWith('+')?'up':'down'}>{a.change}</em></div></button>)}</div><div className="allocation-block"><div className="section-label">资产分布 <span>当前持仓</span></div><div className="allocation-stack">{assets.map(a=><i key={a.code} style={{width:`${a.allocation}%`,background:a.color}}/>)}<i style={{width:'20%',background:'#454b61'}}/></div><div className="allocation-caption"><span>风险资产 <b>80%</b></span><span>现金 <b>20%</b></span></div></div><div className="holding-insight"><ShieldCheck size={16}/><div><b>关注科技资产集中度</b><p>纳指与创业板合计占比 48%</p><button onClick={()=>ask('分析我的持仓风险')}>问问 OwlMate <ArrowUpRight size={13}/></button></div></div></section>
   <section className="panel simulation-panel" id="simulation"><div className="panel-heading"><div><h2>未来情景推演 <span className="purple-tag">SIMULATION</span></h2><p>{focusName} · 当前配置与未来假设</p></div><button className="icon-button" aria-label="放大走势图" onClick={()=>setDialog('chart')}><Expand size={16}/></button></div><div className="chart-toolbar"><Tabs value={scenario} onValueChange={v=>setScenario(v as Scenario)}><TabsList className="scenario-tabs"><TabsTrigger value="bull">上涨</TabsTrigger><TabsTrigger value="base">震荡</TabsTrigger><TabsTrigger value="bear">下跌</TabsTrigger></TabsList></Tabs><Tabs value={String(days)} onValueChange={v=>setDays(Number(v))}><TabsList className="period-tabs">{[5,20,60].map(d=><TabsTrigger key={d} value={String(d)}>{d}日</TabsTrigger>)}</TabsList></Tabs></div>
    <Projection allocation={allocation} days={days} scenario={scenario} selected={selected} deposit={deposit}/>
    <div className="simulation-control"><div className="slider-title"><span><SlidersHorizontal size={14}/>模拟风险资产仓位</span><b>{allocation}<small>%</small><span>现金 {100-allocation}%</span></b></div><Slider value={[allocation]} min={0} max={100} step={5} aria-label="模拟风险资产仓位" onValueChange={v=>setAllocation(Array.isArray(v)?v[0]:v)}/><div className="slider-labels"><span>0% · 全部现金</span><button onClick={()=>setAllocation(80)}>当前实际 80% <RotateCcw size={11}/></button><span>100%</span></div></div>
    <div className="forecast-summary"><div><span>模拟期末资产</span><strong>¥{money(result.end,false)}</strong></div><div><span>{scenarioLabels[scenario]}下的变化</span><strong className={result.pnl>=0?'up':'down'}>{result.pnl>=0?'+':''}{money(result.pnl)}<small>({result.percent>=0?'+':''}{result.percent.toFixed(2)}%)</small></strong></div><button onClick={()=>setDialog('method')}><CircleHelp size={13}/>查看假设</button></div>
   </section></div>
   <section className="lower-grid"><div className="panel events-panel" id="events"><div className="panel-heading"><h2><Radio size={17}/>事件雷达 <span className="count-pill">3</span></h2><span className="muted-small">与你的持仓有关 · 演示</span></div>{events.map((e,i)=><button className="event-row" key={e.title} onClick={()=>{setEventIndex(i);setDialog('event')}}><span className={'event-icon event-'+i}><e.icon size={17}/></span><div><div className="event-title">{e.title}</div><div className="event-meta"><span>{e.type}</span><span>关联：{e.asset}</span></div></div><span className="event-time">{e.time}</span><ChevronRight size={14}/></button>)}</div><div className="panel risk-panel"><div className="panel-heading"><h2><ShieldCheck size={16}/>组合风险透视</h2><span className="amber-tag">值得关注</span></div><div className="risk-main"><div className="risk-dial"><svg viewBox="0 0 160 100" aria-label="示例科技资产占比48%"><path d="M20 85 A60 60 0 0 1 140 85" fill="none" stroke="#292a39" strokeWidth="9" strokeLinecap="round"/><path d="M20 85 A60 60 0 0 1 76 25" fill="none" stroke="#b79af9" strokeWidth="9" strokeLinecap="round"/></svg><div><strong>48<span>%</span></strong><small>科技相关资产</small></div></div><div className="risk-explanation"><b>风格集中</b><p>纳指与创业板可能同向波动，分散标的不等于分散风险。</p></div></div><button className="text-button" onClick={()=>ask('为什么建议降低仓位？')}>了解对我的影响 <ArrowUpRight size={14}/></button></div></section>
   <footer className="page-footer"><span><ShieldCheck size={12}/>演示账户 · 示例行情 · 未接入真实交易</span><span>OwlMate / Make room for perspective.</span></footer>
  </div>
  {chatOpen?<aside className="agent-panel" aria-label="OwlMate 投资助手"><div className="agent-heading"><span className="agent-logo"><Glasses size={23}/></span><div><h2>OwlMate<span>AI</span></h2><p><i/>你的投资思考伙伴</p></div><button className="icon-button" aria-label="收起投资助手" onClick={()=>setChatOpen(false)}><X size={16}/></button></div><div className="agent-context"><Layers3 size={13}/>正在关注：{focusName}<span>演示模式</span></div><div className="agent-scroll"><div className="agent-intro"><span className="eyebrow"><Sparkles size={12}/> PORTFOLIO BRIEF</span><h3>让每一步决策，<br/>都有据可循。</h3><p>{selected<0?'我已整理你的示例组合。今天可以先关注科技资产集中度，再看看不同仓位下的可能结果。':`已切换到${focusName}。中央走势展示该标的的示意路径，下方仓位试算仍以整个账户为基数。`}</p></div>
  <div className="agent-insight"><span className="insight-label"><span className="small-dot"/>当前观察</span><p>{triggered?'科技波动演示事件已触发，建议重新比较下跌情景下的组合表现。':'纳指 ETF 与创业板 ETF 合计占比'}{!triggered&&<strong> 48%</strong>}{!triggered&&'，可以通过保留更多现金，降低组合的波动暴露。'}</p><div className="source-chips"><span>持仓结构</span><span>画像约束</span><span>情景假设</span></div></div>
  <div className="recommendation"><div className="recommend-heading"><Sparkles size={15}/><b>仓位试算</b><span>可调整</span></div><div className="position-change"><div><span>当前仓位</span><strong>80<small>%</small></strong></div><ArrowRight size={22}/><div><span>模拟仓位</span><strong>{allocation}<small>%</small></strong></div></div><div className="position-track"><span style={{width:`${allocation}%`}}/><i style={{left:'80%'}}/></div><div className="recommend-detail"><span>模拟现金</span><b>¥{money(result.cash,false)}</b></div><div className="recommend-detail"><span>风险资产调整额</span><b>{result.riskyDelta>=0?'+':'−'}¥{money(Math.abs(result.riskyDelta),false)}</b></div><p className="recommend-note">演示配置，非凯利计算。调整后各风险资产按原比例分配。</p><button className="save-button" onClick={save}><Bookmark size={15}/>保存试算方案<ArrowRight size={15}/></button></div>
  <div className="ask-prompts"><span>继续探索</span>{['为什么建议降低仓位？','如果市场下跌呢？'].map(q=><button key={q} onClick={()=>ask(q)} disabled={pending}>{q}<ArrowUpRight size={14}/></button>)}</div>
  <div className="chat-history" aria-live="polite">{messages.map((m,i)=><div className={'message '+m.role} key={i}>{m.role==='assistant'&&<span className="message-author"><Glasses size={15}/>OwlMate · 演示回复</span>}<p>{m.text}</p></div>)}{pending&&<div className="thinking"><i/><i/><i/><span>正在整理试算…</span></div>}<div ref={chatEnd}/></div></div>
  <form className="chat-composer" onSubmit={e=>{e.preventDefault();ask(input)}}><div className="composer-box"><textarea ref={inputRef} aria-label="与 OwlMate 交流" placeholder="问问 OwlMate，或试试“仓位调到 60%”" value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();ask(input)}}} rows={2}/><div><span><Sparkles size={12}/>结合当前组合回答</span><button type="submit" aria-label="发送消息" disabled={!input.trim()||pending}><ArrowUpRight size={18}/></button></div></div><p>演示回复与假设推演，不构成实际投资建议</p></form></aside>:<button className="open-chat primary-button" onClick={()=>setChatOpen(true)}><MessageSquare size={18}/>OwlMate 助手</button>}
  </main></div>
  {notice&&<div className="notice" role="status"><Check size={17}/>{notice}</div>}
  <Dialog open={dialog!==null} onOpenChange={v=>{if(!v)setDialog(null)}}><DialogContent className={'owl-dialog '+(dialog==='chart'?'chart-dialog':'')}><DialogTitle>{({profile:'我的投资画像',plan:'新资金配置试算',saved:'已保存的试算方案',chart:`${focusName} · 未来情景推演`,event:'事件详情',method:'数据与模拟说明'} as Record<string,string>)[dialog??'method']}</DialogTitle><DialogDescription>{dialog==='chart'?'历史与未来均为示意，非真实行情或预测。':'OwlMate 首页演示 · 所有资产、行情和事件均为示例'}</DialogDescription>
   {dialog==='profile'&&<div className="dialog-body"><label>投资目标<select value={risk} onChange={e=>setRisk(e.target.value)}><option>稳健成长</option><option>长期增长</option><option>重视流动性</option></select></label><label>资金可投资期限<select value={months} onChange={e=>setMonths(e.target.value)}><option>3 个月</option><option>12 个月</option><option>3 年以上</option></select></label><div className="info-box">当前真实风险资产仓位：80%<br/>账户基数：¥1,286,400<br/>本页画像只保留在当前会话，模拟不改变真实持仓。</div><button className="primary-button" onClick={()=>{setAllocation(risk==='重视流动性'||months==='3 个月'?40:risk==='长期增长'?75:65);setDialog(null);setNotice('画像已更新，对应的演示仓位已载入试算。')}}>应用到演示方案<ArrowRight size={15}/></button></div>}
   {dialog==='plan'&&<form className="dialog-body" onSubmit={e=>{e.preventDefault();const amount=Number(depositDraft);if(!Number.isFinite(amount)||amount<0||amount>10000000)return;setDeposit(amount);setDialog(null);setNotice('新增资金已加入模拟基数，实际账户余额未改变。')}}><label>新增资金金额（元）<input type="number" min="0" max="10000000" step="100" value={depositDraft} onChange={e=>setDepositDraft(e.target.value)} required/></label><div className="amount-options">{[20000,50000,100000].map(n=><button type="button" key={n} className={depositDraft===String(n)?'chosen':''} onClick={()=>setDepositDraft(String(n))}>{n/10000} 万元</button>)}</div><div className="info-box">将以现有资产加新增资金计算配置。当前模拟风险资产仓位 {allocation}%，现金 {100-allocation}%。</div><button className="primary-button" type="submit">生成配置试算<ArrowRight size={15}/></button></form>}
   {dialog==='saved'&&<div className="dialog-body">{saved?<><div className="saved-title"><Bookmark size={22}/><div><b>我的组合 · 情景方案</b><small>{saved.at}</small></div></div><div className="saved-grid"><div>风险资产<strong>{saved.allocation}%</strong></div><div>模拟周期<strong>{saved.days} 日</strong></div><div>市场情景<strong>{scenarioLabels[saved.scenario]}</strong></div><div>新增资金<strong>¥{money(saved.deposit,false)}</strong></div></div><p className="muted">方案保存在此浏览器，未连接券商或执行交易。</p><button className="primary-button" onClick={()=>{setAllocation(saved.allocation);setDays(saved.days);setScenario(saved.scenario);setDeposit(saved.deposit);setDialog(null);setNotice('已恢复保存的模拟方案。')}}>载入此方案<ArrowRight size={15}/></button></>:<div className="empty-state"><Bookmark size={32}/><h3>还没有保存的方案</h3><p>调整中央模拟仓位，再点击助手中的「保存试算方案」。</p></div>}</div>}
   {dialog==='chart'&&<Projection allocation={allocation} days={days} scenario={scenario} selected={selected} deposit={deposit} large/>}
   {dialog==='event'&&<div className="dialog-body"><span className="purple-tag">虚构演示事件 · {events[eventIndex].time}</span><h3>{events[eventIndex].title}</h3><p>{events[eventIndex].desc}</p><div className="info-box">关联资产：{events[eventIndex].asset}<br/>证据状态：演示内容，未核实真实市场信息</div><button className="primary-button" onClick={()=>{setTriggered(true);setDialog(null);ask(eventIndex===0?'科技事件对我有什么影响？':eventIndex===1?'分析我的持仓风险':'为什么建议降低仓位？')}}>让 OwlMate 分析影响<ArrowRight size={15}/></button></div>}
   {dialog==='method'&&<div className="dialog-body"><p>首页行情、历史曲线、收益和事件都是虚构示例。未来图为归一化情景示意，阴影不是概率区间。</p><div className="info-box">20 日风险资产收益假设：上涨 +8%、震荡 +1.5%、下跌 −10%。其他周期按复利缩放。现金收益假设为零，模拟换仓成本为调整金额的 0.1%。</div><p>数字试算基于整个组合，风险资产按现有权重同比例调整。{days} 日{scenarioLabels[scenario]}下，维持当前 80% 配置的模拟期末资产为 ¥{money(original.end,false)}。</p><p>凯利仓位、EV 评分、蒙特卡洛概率和真实 AI 尚未接入。对话使用预设意图响应；策略、画像和资讯仍需后续验证。</p></div>}
  </DialogContent></Dialog>
 </div>
}
