'use client';
import {useState} from 'react';
import {ArrowRight,Bookmark,ListChecks,Sparkles} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {type Account,summarize} from '@/lib/holdings';
import {forecast,money,scenarioLabels,type Scenario} from '@/lib/simulation';
export function StrategyWorkbench({account,allocation,days,scenario,deposit,onSave}:{account:Account;allocation:number;days:number;scenario:Scenario;deposit:number;onSave:()=>void}){
 const [dialog,setDialog]=useState<'details'|null>(null);
 const s=summarize(account),base=s.total+deposit;
 const unchangedAllocation=base?s.marketValue/base*100:0;
 const before=forecast(unchangedAllocation,days,scenario,deposit,s),after=forecast(allocation,days,scenario,deposit,s);
 const unsupported=s.marketValue===0&&allocation>0;
 const rows=s.assets.map(h=>{const target=after.risky*h.value/s.marketValue;return {...h,target,delta:target-h.value,targetWeight:after.total-after.cost?target/(after.total-after.cost)*100:0}});
 const difference=after.end-before.end;
 return <section className="strategy-workbench compact-strategy" id="strategy"><div className={`panel comparison-panel compact-comparison scenario-${scenario}`}><div className="compact-strategy-heading"><div><h2><Sparkles size={16}/>未来建议与方案对比</h2><p>{days} 日 · {scenarioLabels[scenario]} · 模拟演示</p></div><span className="compact-target">目标仓位 <b>{allocation.toFixed(1)}%</b></span></div><div className="compact-strategy-body"><div className="future-recommendation"><span>未来建议</span><strong>{unsupported?'先添加投资标的':allocation<unchangedAllocation?'降低风险暴露，保留更多现金':allocation>unchangedAllocation?'提高风险暴露，分批调整':'维持当前仓位，继续观察'}</strong><small>{unsupported?'当前账户没有可分配的风险资产。':`风险资产由 ${unchangedAllocation.toFixed(1)}% 调整至 ${allocation.toFixed(1)}%，模拟现金 ¥${money(after.cash)}。`}</small></div><div className="compact-comparison-route"><div><span>维持现状</span><strong>¥{money(before.end,false)}</strong><small>盈亏 {before.pnl>=0?'+':''}{money(before.pnl)}</small></div><ArrowRight size={18}/><div className="proposed"><span>当前方案</span><strong>{unsupported?'暂不可计算':`¥${money(after.end,false)}`}</strong><small>盈亏 {after.pnl>=0?'+':''}{money(after.pnl)}</small></div><em className={difference>=0?'up':'down'}>{difference>=0?'+':'−'} ¥{money(Math.abs(difference),false)}</em></div><div className="compact-facts"><span>模拟现金 <b>¥{money(after.cash)}</b></span><span>调仓成本 <b>¥{money(after.cost)}</b></span><span>新增资金 <b>¥{money(deposit)}</b></span></div><div className="compact-strategy-actions"><button className="secondary-button" onClick={()=>setDialog('details')}><ListChecks size={15}/>调仓明细</button><button className="primary-button" disabled={unsupported||base<=0} onClick={onSave}><Bookmark size={15}/>保存方案</button></div></div></div>
 <Dialog open={dialog!==null} onOpenChange={v=>{if(!v)setDialog(null)}}><DialogContent className={'owl-dialog '+(dialog==='details'?'trade-dialog':'')}><DialogTitle>{dialog==='details'?'逐项调仓明细':'策略检查条件'}</DialogTitle><DialogDescription>{dialog==='details'?'按当前风险资产的相对权重分配目标金额。金额试算未做整手取整，不是可直接下单的数量。':'使用手动维护的账户数据，在页面内检查仓位偏离。'}</DialogDescription>< ><div className="trade-rows">{rows.map(h=><div className="trade-row" key={h.id}><div><b>{h.name}</b><small>{h.code}</small></div><div><small>当前 → 目标市值</small><span>¥{money(h.value)} → ¥{money(h.target)}</span></div><div><small>调整金额 · 目标占比 {h.targetWeight.toFixed(1)}%</small><b className={h.delta>=0?'up':'down'}>{Math.abs(h.delta)<.005?'不调整':`${h.delta>=0?'增加':'减少'} ¥${money(Math.abs(h.delta))}`}</b></div></div>)}{!rows.length&&<p>暂无持仓，不能生成逐项配置。</p>}</div><div className="info-box">新增资金：¥{money(deposit)}<br/>调整后现金：¥{money(after.cash)}<br/>费用合计：¥{money(after.cost)}<br/>资产守恒：目标持仓＋目标现金＋费用＝当前资产＋新增资金。</div><button className="primary-button" disabled={unsupported||base<=0} onClick={()=>{onSave();setDialog(null)}}>保存方案</button></></DialogContent></Dialog>
 </section>
}
